import { boolean, integer, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";

export const foundingDriverLeads = pgTable("founding_driver_leads", {
  id: uuid("id").defaultRandom().primaryKey(),
  fullName: text("full_name").notNull(),
  email: text("email").notNull().unique(),
  phone: text("phone"),
  city: text("city"),
  currentApps: text("current_apps").array(),
  yearsDriving: integer("years_driving"),
  driverType: text("driver_type"),
  vehicleType: text("vehicle_type"),
  vehicleYear: integer("vehicle_year"),
  vehicleMakeModel: text("vehicle_make_model"),
  hasCommercialInsurance: boolean("has_commercial_insurance"),
  interestedInAirport: boolean("interested_in_airport"),
  airportExperience: text("airport_experience"),
  preferredZones: text("preferred_zones").array(),
  source: text("source"),
  referralCode: text("referral_code").unique(),
  referralName: text("referral_name"),
  referredByCode: text("referred_by_code"),
  status: text("status").default("new").notNull(),
  leadScore: integer("lead_score").default(0).notNull(),
  wantsDemoAccess: boolean("wants_demo_access").default(false).notNull(),
  wantsWhatsAppInvite: boolean("wants_whatsapp_invite").default(false).notNull(),
  consentContact: boolean("consent_contact").default(false).notNull(),
  consentVerification: boolean("consent_verification").default(false).notNull(),
  consentPrivacy: boolean("consent_privacy").default(false).notNull(),
  followUpAt: timestamp("follow_up_at", { withTimezone: true }),
  lastContactedAt: timestamp("last_contacted_at", { withTimezone: true }),
  adminNotes: text("admin_notes"),
  notes: text("notes"),
  ipAddress: text("ip_address"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

export const investorInterestLeads = pgTable("investor_interest_leads", {
  id: uuid("id").defaultRandom().primaryKey(),
  fullName: text("full_name").notNull(),
  email: text("email").notNull().unique(),
  phone: text("phone"),
  leadType: text("lead_type").notNull(),
  interestRange: text("interest_range"),
  accredited: text("accredited"),
  interestType: text("interest_type"),
  preferredNextStep: text("preferred_next_step"),
  source: text("source"),
  referralCode: text("referral_code"),
  referralName: text("referral_name"),
  status: text("status").default("new").notNull(),
  leadScore: integer("lead_score").default(0).notNull(),
  wantsDemoAccess: boolean("wants_demo_access").default(false).notNull(),
  wantsInvestorDeck: boolean("wants_investor_deck").default(false).notNull(),
  wantsWhatsAppInvite: boolean("wants_whatsapp_invite").default(false).notNull(),
  consentContact: boolean("consent_contact").default(false).notNull(),
  consentNotOffering: boolean("consent_not_offering").default(false).notNull(),
  consentPrivacy: boolean("consent_privacy").default(false).notNull(),
  followUpAt: timestamp("follow_up_at", { withTimezone: true }),
  lastContactedAt: timestamp("last_contacted_at", { withTimezone: true }),
  adminNotes: text("admin_notes"),
  message: text("message"),
  ipAddress: text("ip_address"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

export type FoundingDriverLead = typeof foundingDriverLeads.$inferSelect;
export type InsertFoundingDriverLead = typeof foundingDriverLeads.$inferInsert;
export type InvestorInterestLead = typeof investorInterestLeads.$inferSelect;
export type InsertInvestorInterestLead = typeof investorInterestLeads.$inferInsert;
